#!/usr/bin/env bash
# Emits the Homebrew formula for a released version.
#
# The formula installs the release fat jar and a wrapper script, rather than building from source:
# a Homebrew build would need the whole Gradle toolchain, and the jar is already published and
# checksummed by the release workflow. `using: :nounzip` matters -- a .jar *is* a zip, so without it
# Homebrew helpfully unpacks the archive and the formula ends up with loose class files instead of
# the jar it asked for.
#
# Usage: scripts/generate-homebrew-formula.sh <version> [output-path]
#   scripts/generate-homebrew-formula.sh 0.2.6-alpha Formula/droidagent.rb
set -euo pipefail

VERSION="${1:-}"
OUTPUT="${2:-/dev/stdout}"
REPO="iVamsi/droid-agent-kit"

if [ -z "$VERSION" ]; then
  echo "usage: $0 <version> [output-path]" >&2
  exit 2
fi

JAR="droidagent-cli-${VERSION}.jar"
URL="https://github.com/${REPO}/releases/download/v${VERSION}/${JAR}"

# The checksum comes from the release's own .sha256 asset rather than being recomputed here, so the
# formula pins exactly what the release workflow published. A locally rebuilt jar is not
# byte-identical and would produce a checksum no user could reproduce.
echo "generate-homebrew-formula: fetching published checksum for $VERSION" >&2
SHA="$(curl -fsSL "${URL}.sha256" | awk '{print $1}')"
if ! printf '%s' "$SHA" | grep -qE '^[0-9a-f]{64}$'; then
  echo "generate-homebrew-formula: no valid sha256 at ${URL}.sha256 (got: ${SHA:-empty})" >&2
  echo "  Has v${VERSION} been released yet?" >&2
  exit 1
fi

cat > "$OUTPUT" <<EOF
# Generated by scripts/generate-homebrew-formula.sh -- do not edit by hand.
class Droidagent < Formula
  desc "Android development MCP server: Gradle, adb, logcat, crash triage, Perfetto"
  homepage "https://github.com/${REPO}"
  url "${URL}", using: :nounzip
  sha256 "${SHA}"
  license "Apache-2.0"
  version "${VERSION}"

  depends_on "openjdk@17"

  def install
    libexec.install "${JAR}"
    (bin/"droidagent").write <<~SH
      #!/bin/bash
      exec "#{Formula["openjdk@17"].opt_bin}/java" -jar "#{libexec}/${JAR}" "\$@"
    SH
    chmod 0755, bin/"droidagent"
  end

  def caveats
    <<~EOS
      Register the MCP server with your agent:
        droidagent install-mcp

      Check your environment first if anything misbehaves:
        droidagent doctor
    EOS
  end

  test do
    # Exercises the real entry point: the wrapper must find the JRE and the jar must run.
    # Deliberately only --help -- the CLI has no --version flag, and asserting one would fail
    # \`brew test\` on every install.
    output = shell_output("#{bin}/droidagent --help")
    assert_match "serve-mcp", output
    assert_match "doctor", output
  end
end
EOF

if [ "$OUTPUT" != "/dev/stdout" ]; then
  echo "generate-homebrew-formula: wrote $OUTPUT" >&2
fi
