#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
REF="${RESTORE_REF:-d19d517f09e79ad234ab6ceaa9aee87e7769f96c}"

if ! git rev-parse --verify "${REF}^{commit}" >/dev/null 2>&1; then
  echo "Commit ${REF} not in local repo. Run: git fetch origin main" >&2
  exit 1
fi

git show "${REF}:gradle/verification-metadata.xml" > gradle/verification-metadata.xml

python3 - <<'PY'
from pathlib import Path
path = Path("gradle/verification-metadata.xml")
text = path.read_text()
needle = """         <artifact name="junit-bom-5.12.2.pom">
            <sha256 value="cef80fec86454f6806bfb0df24669b5c6f32e2cb728539ea859f47dfdc9bbc17" origin="Generated by Gradle"/>
         </artifact>
      </component>
      <component group="org.slf4j"""
insert = """         <artifact name="junit-bom-5.12.2.pom">
            <sha256 value="cef80fec86454f6806bfb0df24669b5c6f32e2cb728539ea859f47dfdc9bbc17" origin="Generated by Gradle"/>
         </artifact>
         <artifact name="junit-bom-5.12.2.module">
            <sha256 value="de70ac5d91a52656d8890a6d23b9e04d99b99b1a0402530decad71bf31b2735e" origin="Generated by Gradle"/>
         </artifact>
      </component>
      <component group="org.slf4j"""
if "junit-bom-5.12.2.module" not in text:
    if needle not in text:
        raise SystemExit("junit-bom anchor not found in verification-metadata.xml")
    path.write_text(text.replace(needle, insert, 1))
PY
echo "Restored gradle/verification-metadata.xml with junit-bom-5.12.2.module"
